### ISSUE TITLE
Overlap with com.megaphonetech.checksums

### ISSUE THREAD

**Issue by colemanw** [CiviCooP/org.civicoop.validatechecksumapi#1]
There is some overlap between this extension and com.megaphonetech.checksums.  Although this one came first I think the other one is using the symantics of the api better (IMO a "checksum" is not an entity, but a pseudo-property of the Contact entity) and the other extension has the ability to not only validate but also generate them.

FYI in Api v4 neither extension will be needed because the `getChecksum` and `validateChecksum` actions are included :)

**Comment by colemanw** [comment]
See https://github.com/MegaphoneJon/com.megaphonetech.checksums/issues/1

**Comment by ErikHommel** [comment]
Thanks @colemanw I will remove the repo.
